### ISSUE TITLE
All sketchmaps stored in memory

### ISSUE THREAD

**Issue by trainphreak** [trainphreak/SketchMap#4]
All sketchmaps are loaded into memory from onEnable(). On large servers, this could take a very long time. The initial parse of the sketchmaps is necessary so the plugin knows what sketchmaps exist, but let's see if we can find a way to have the renderer for a particular sketchmap be loaded the first time a player wants to view the sketchmap, rather than when the server starts.

**Comment by trainphreak** [comment]
This is why I shouldn't make comments on things I haven't looked into. The sketchmaps are all loaded because the plugin uses custom map renderers to display the maps, and storing in memory is a better choice here than storing on disk only.

**Comment by trainphreak** [comment]
It may not be possible to load the actual picture data only when needed, but what if we took the images being stored and resized the image data to match the number of pixels in the Sketchmap they are in?

**Comment by mibby** [comment]
@trainphreak Any plans on continuing work on this issue? :D 

What if an image was mapped dynamically to a map so it doesn't have to be loading a sketchmap file into memory? i.e. saving the map file copy on disk to the world folder directly so if you removed sketchmap, the displayed image map would still be functional and read from there?

**Comment by trainphreak** [comment]
Right now, Sketchmap replaces the default map-item renderer so it displays the image instead of the block data. I suppose that, with some science-ing (meaning breaking things to figure out how they work), the image might be able to be written directly, but it would probably come with the danger of players accidentally overwriting the image with regular map data.

It's not as good as dynamic loading of the images to save memory, but my earlier idea of resizing downloaded images would at least reduce the memory consumed by each one.

**Comment by mibby** [comment]
I see. How much of a memory overhead is there in caching all the images? Is it just the size of the .sketchmap file?

I'm assuming dynamic loading of the images would work similarly to this plugin.
https://www.spigotmc.org/resources/bannerboard.20435/

I'll be here to help test and debug problems whenever you do begin experimenting and continuing work on your SketchMaps fork. :) Currently using your fork with this extra commit. https://github.com/connection-lost/SketchMap/commit/0020e49e8260dde3f5e901486c8b05d5b1f04db7 And if not done so already, might want to look into processing images asynchronously to avoid the server timings out (https://github.com/slipswhitley/SketchMap/issues/3).

**Comment by mibby** [comment]
Still here to help test. Any optimizations that can be squeezed out of the plugin. :)

**Comment by mibby** [comment]
@trainphreak Is there any way to speed up the initial sketchmap loading process at start-up? I have a bunch of small-ish maps used (no larger than 3x5), that seem to be slowing server startup / reboot quite a bit. Gets longer the more maps created.

```
[15:25:44] [Server thread/INFO]: [SketchMap] Enabling SketchMap v1.4.2
[15:25:45] [Server thread/INFO]: [SketchMap] 10/38 sketchmaps loaded.
[15:25:47] [Server thread/INFO]: [SketchMap] 20/38 sketchmaps loaded.
[15:25:48] [Server thread/INFO]: [SketchMap] 30/38 sketchmaps loaded.
[15:25:49] [Server thread/INFO]: [SketchMap] Finished! 38 sketchmaps loaded
```

**Comment by trainphreak** [comment]
It's a side effect of storing the images in base64 and using a custom renderer, which requires loading every image into memory. I've been toying with a way to write the image directly into each map's NBT data, which would remove the loading requirement and drastically shrink the size of the plugin's data folder, but I've been pretty busy lately :/

**Comment by mibby** [comment]
All good. I'll still be here when you do manage to find the time to mess around with the loading and converting. :)

**Comment by mibby** [comment]
Do you have any ideas when you will be free to mess around with sketchmap loading / behavior testing?

**Comment by mibby** [comment]
Another alternative solution to look into may be to reserve a specific set of map ids (configurable, such as IDs 500-1000) to write the map data to and just overwrite on those ids if there are no more free map images to use. That way you won't be permanently using up the theoretical maximum of 65k map ids when creating / testing sketchmap images. And because they would be reserved, you could write directly to them to avoid having to convert every time at startup and not worry about it being overwritten by a player?

**Comment by mibby** [comment]
@trainphreak Perhaps as a temporary stop-gate, would it be possible to move the sketchmap loading post start-up to prevent start-up delay or use multi-threading to load the map conversions behind the scenes and simultaneously instead of progressively one at a time to prevent long load time with many maps?

**Comment by mibby** [comment]
Still interested in any optimizations due to how long start-up time takes. :(

```
[11:16:34] [Server thread/INFO]: [SketchMap] Enabling SketchMap v1.4.2
[11:16:36] [Server thread/INFO]: [SketchMap] 10/32 sketchmaps loaded.
[11:16:37] [Server thread/INFO]: [SketchMap] 20/32 sketchmaps loaded.
[11:16:39] [Server thread/INFO]: [SketchMap] 30/32 sketchmaps loaded.
[11:16:39] [Server thread/INFO]: [SketchMap] Finished! 32 sketchmaps loaded
```

**Comment by trainphreak** [comment]
In between moving halfway across the US for a new job and getting settled
in said job, I got fed up with everything breaking if the plugin wasn't
loaded and wrote a whole new version that writes the picture directly into
the map data instead of just replacing the renderer. It will probably be
released once I get it updated to 1.12, which mostly means adding the 64
new colors so it will actually use them. Still debating whether to release
it for free or as a cheap ($1-2) premium plugin though.

**Comment by mibby** [comment]
Any update on start-up optimizing? Still not a huge fan of the slowed down start-up time. :(

```
[03:13:20] [Server thread/INFO]: [SketchMap] Enabling SketchMap v1.4.2
[03:13:21] [Server thread/INFO]: [SketchMap] 10/32 sketchmaps loaded.
[03:13:22] [Server thread/INFO]: [SketchMap] 20/32 sketchmaps loaded.
[03:13:24] [Server thread/INFO]: [SketchMap] 30/32 sketchmaps loaded.
[03:13:24] [Server thread/INFO]: [SketchMap] Finished! 32 sketchmaps loaded
```

**Comment by trainphreak** [comment]
Okay, Slips (original author) was attempting to stay active with development (which didn't happen), so that's why I never really implemented the whole "save image data in the world folder" thing with Sketchmap. To retain source code control and not step on toes by doing a forced takeover of the plugin, I wrote a whole new plugin that does mostly the same thing as Sketchmap, but it does some things better, like multithreaded image processing (instead of main thread) and storing images directly in the map data (instead of text files that have to be parsed and using a custom map renderer).

https://www.spigotmc.org/resources/picmap.50826/

You probably already expected this since I haven't really been active with this plugin for over a year, but I'm officially discontinuing my work on Sketchmap.
